### PR TITLE
Experimental Node 10

### PR DESCRIPTION
**Pull request by Drapegnik**
try to use [`@babel/preset-env`](http://babeljs.io/docs/en/next/babel-preset-env) to avoid compiling features, that supported with `node v.10`

### CODE REVIEW

**Comment by Drapegnik** [comment]
@UladBohdan tests passed! (except one strange with Diary). Could you please install `node@10` on our servers through [`nvm`](https://github.com/creationix/nvm)?

**Comment by Drapegnik** [comment]
[migrate to node@10](https://trello.com/c/yLsz8c2E/71-migrate-to-node10)

**Comment by UladBohdan** [comment]
Weird diary test case not passing is ok:(

**Comment by UladBohdan** [comment]
And I'm afraid we're not using nvm on our servers.
But anyway
Once this is merged I can make it work on the servers

**Pull request merged**
